### PR TITLE
Fix integration with MXNet nightly build

### LINKED ISSUE #1217: MXNet cu100-pre broke docker build on CPU machine
**Environment:**
1. Framework: MXNet
2. Framework version: mxnet-cu100 --pre
3. Horovod version: master
4. MPI version: 3.0.0
5. CUDA version: 10.0
6. NCCL version: 2.4.7
7. Python version: 2.7
8. OS and version: Ubuntu 16.04
9. GCC version: 5.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

https://buildkite.com/horovod/horovod/builds/710#7d3ba97d-0126-4117-b04a-cae10bdc9767

```
/usr/bin/g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/horovod/common/common.o build/temp.linux-x86_64-2.7/horovod/common/fusion_buffer_manager.o build/temp.linux-x86_64-2.7/horovod/common/half.o build/temp.linux-x86_64-2.7/horovod/common/message.o build/temp.linux-x86_64-2.7/horovod/common/mpi_context.o build/temp.linux-x86_64-2.7/horovod/common/operations.o build/temp.linux-x86_64-2.7/horovod/common/parameter_manager.o build/temp.linux-x86_64-2.7/horovod/common/response_cache.o build/temp.linux-x86_64-2.7/horovod/common/timeline.o build/temp.linux-x86_64-2.7/horovod/common/ops/collective_operations.o build/temp.linux-x86_64-2.7/horovod/common/ops/mpi_operations.o build/temp.linux-x86_64-2.7/horovod/common/ops/operation_manager.o build/temp.linux-x86_64-2.7/horovod/common/optim/bayesian_optimization.o build/temp.linux-x86_64-2.7/horovod/common/optim/gaussian_process.o build/temp.linux-x86_64-2.7/horovod/common/logging.o build/temp.linux-x86_64-2.7/horovod/common/ops/cuda_operations.o build/temp.linux-x86_64-2.7/horovod/common/ops/mpi_cuda_operations.o build/temp.linux-x86_64-2.7/horovod/common/ops/nccl_operations.o build/temp.linux-x86_64-2.7/horovod/torch/mpi_ops_v2.o build/temp.linux-x86_64-2.7/horovod/torch/handle_manager.o build/temp.linux-x86_64-2.7/horovod/torch/ready_event.o build/temp.linux-x86_64-2.7/horovod/torch/cuda_util.o build/temp.linux-x86_64-2.7/horovod/torch/adapter_v2.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib64 -lcudart -lnccl_static -lcudart -o build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib_v2.so -Wl,--version-script=horovod.lds -I/usr/local/include -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -L/usr/local/lib -lmpi
--
  | terminate called after throwing an instance of 'dmlc::Error'
  | what():  [01:22:52] include/mxnet/base.h:427: Check failed: e == cudaSuccess (35 vs. 0) :  CUDA: CUDA driver version is insufficient for CUDA runtime version
  | Stack trace:
  | [bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x4b1deb) [0x7f4b76b93deb]
  | [bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x253cc04) [0x7f4b78c1ec04]
  | [bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x2725e1) [0x7f4b769545e1]
  | [bt] (3) /lib64/ld-linux-x86-64.so.2(+0x106ca) [0x7f4ce813f6ca]
  | [bt] (4) /lib64/ld-linux-x86-64.so.2(+0x107db) [0x7f4ce813f7db]
  | [bt] (5) /lib64/ld-linux-x86-64.so.2(+0x158f2) [0x7f4ce81448f2]
  | [bt] (6) /lib64/ld-linux-x86-64.so.2(+0x10574) [0x7f4ce813f574]
  | [bt] (7) /lib64/ld-linux-x86-64.so.2(+0x14db9) [0x7f4ce8143db9]
  | [bt] (8) /lib/x86_64-linux-gnu/libdl.so.2(+0xf09) [0x7f4ce7944f09]
```

@apeforest @yuxihu, could you take a look?

### PR DESCRIPTION
**Pull request by yuxihu**
Due to a new set of [APIs](https://github.com/apache/incubator-mxnet/pull/15551) introduced in recent MXNet master branch, we hit [undefined symbol error](https://github.com/horovod/horovod/issues/1217) when running Horovod with nightly MXNet build. This PR fixes #1217 and https://github.com/apache/incubator-mxnet/issues/15578 by using C API.

### CODE REVIEW

**Comment by yuxihu** [comment]
@apeforest @alsrgv Please help review. Thanks.

**Comment by yuxihu** [comment]
The CI failed on Torch test and is unrelated to the change in this PR.

File: horovod/mxnet/tensor_util.cc [hunk 1]
```diff
@@ -123,14 +123,14 @@ int TensorUtil::GetDevice(NDArray* tensor) {
 // If dev_id equal to CPU_DEVICE_ID, construct Tensor on CPU
 // Otherwise construct on GPU
 NDArray* TensorUtil::New(int device, int dtype) {
+  int dev_type = gpu::kDevMask;
```
Comment (apeforest) [inline horovod/mxnet/tensor_util.cc]: Wouldn't it be cleaner to use a ternary operator here as:
```suggestion
  int dev_type = (device == CPU_DEVICE_ID) ? cpu::kDevMask: gpu::kDevMask;
```

**Comment by apeforest** [comment]
One small comment otherwise LGTM.

File: horovod/mxnet/tensor_util.cc (hunk 1 above)
Comment (yuxihu) [reply horovod/mxnet/tensor_util.cc]: I also need to set the device to 0 if it is CPU. I will need to have two such ternary operator statements, which does not differ much with the current one.
